### ISSUE TITLE
Communication between the Automation module and Security Panel

### ISSUE THREAD

**Issue by patelneel55** [darconeous/concordd#4]
Hey @darconeous,

I had a question regarding the communication process between the raspberry pi, the automation module and the security panel. I couldn't find a better way to contact you, that's why I created the issue. 

When I run the "refresh" command, the RS232 LED in the automation module seems to blink notifying that the command has been sent to the Security Panel, however I don't seem to be receiving data back because when I run either the "system" or the "zone" commands it is still set to default values.

Would you happen to have an idea of what could be the point of failure? The connection between the pi and the auto module or the connection between the auto module and the panel?

**Comment by mralapete** [comment]
You’ve a comms problem between the RPI and the AM module. Try a different rs232 to Usb cable. There are two different chipsets in those cables. If you do a bit of searching you will find quite a bit on that subject.

**Comment by mralapete** [comment]
The choice of chipsets are FTDI or Prolific chipset. The Prolific chipset is generally preferred but this is interesting to read https://hackaday.com/2016/02/01/ftdi-drivers-break-fake-chips-again/

Try where possible to get yourself a genuine cable to avoid problems you are experiencing now.

**Comment by patelneel55** [comment]
I have a Prolific chipset in the current adapter. I tried configuring the serial port using the `minicom` command to set it to the specified 9600 baud rate with odd parity but still to no avail. I ordered another another adapter cable to make sure the current one is not faulty.

**Comment by patelneel55** [comment]
I contacted Interlogix, the module manufacturer, for some more info and apparently the automation module is not compatible with the Concord 4 Express as it does not support automation channels even though their installation instructions says that it is compatible with the Concord 4 and the Concord 4 Express.

Regardless, thank you for your help and insight,  I got to learn something new about RS232 cable chipsets.

**Comment by mralapete** [comment]
According to this information it does support the Concord 4 Express https://static.interlogix.com/library/466-1876-C_superbus_2000_rs-232_automation_module_install_instr.pdf

**Comment by mralapete** [comment]
It depends what version of software your Concord 4 Express panel is running. If you want to try and resolve this post back and let me know.

**Comment by zzeitlin** [comment]
How do you determine whether your board is a concord 4 or concord 4 express?

**Comment by mralapete** [comment]
On the hardware side the Concord Express only supports 16 wireless sensors. 

Go to your keypad and press 9 followed by your installer code press A until your see System Version. Press # and press B until you see SW Version. This should be greater than 025x to use the automation module.

A final check. On the main board you will see the CPU chip. It should have a sticker attached to it stating the software version.
